kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployment
spec:
  replicas: 2
  selector: 
    matchLabels: 
       app: myspringbootapp
  template:
    metadata:
      labels:
        app: myspringbootapp
    spec:
     containers:
       - name: myspringbootapp
         image: vikashashoke/mrdevops_java_webapplication_ci:latest
         imagePullPolicy: Always
         ports:
           - containerPort: 9090
  
    